version: 2.1

jobs:
  build:
    working_directory: ./Main
    docker:
      - image: "circleci/python:3.9.9"
    steps:
      - checkout
      - run: python3 UseCase.py
  test:
    working_directory: ./Test
    docker:
      - image: "circleci/python:3.9.9"
    steps:
      - checkout
      - run: python3 MCCTest.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
