version: 2.1

jobs:
  build:
    working_directory: /Users/pawelpolski/Desktop/ModifiedClusterCentroids
    docker:
      - image: "circleci/python:3.9.9"
    steps:
      - checkout
      - run: python3 Main/UseCase.py
  test:
    working_directory: /Users/pawelpolski/Desktop/ModifiedClusterCentroids
    docker:
      - image: "circleci/python:3.9.9"
    steps:
      - checkout
      - run: python3 Test/MCCTest.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
